<?php

namespace Application\Tests\Unit\Strategy\CommissionCalculator;

use PHPUnit\Framework\TestCase;
use Application\Tests\Unit\BaseTest;
use Application\Strategy\CommissionCalculator\CurrencyIsEuro;
use Application\Strategy\CommissionCalculator\DifferentCurrency;
use Application\Strategy\CommissionCalculator\AmountCalculationStrategy;

class DifferentCurrencyTest extends TestCase
{
    private AmountCalculationStrategy $instance;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->instance = new DifferentCurrency();
    }

    public function test_amount_with_rate_counts_correctly()
    {
        $this->assertEquals($this->instance->calculateAmount(100.5, 2), 50.25);
        $this->assertEquals($this->instance->calculateAmount(100, 1.3), 76.92);
    }
}